"""
Audio Routes

All /api/audio/* and /api/tts/* endpoints
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from .dependencies import get_tts_service

router = APIRouter(tags=["audio"])


@router.get("/api/audio/{filename}")
async def get_audio(filename: str):
    """
    Serve cached audio files
    
    Audio is generated by TTS service and cached.
    """
    tts_service = get_tts_service()
    
    audio_data = await tts_service.get_audio(filename)
    if not audio_data:
        raise HTTPException(status_code=404, detail="Audio file not found")
    
    return StreamingResponse(
        iter([audio_data]),
        media_type="audio/mpeg",
        headers={"Content-Disposition": f"inline; filename={filename}"},
    )


@router.post("/api/tts/clear-cache")
async def clear_tts_cache():
    """Clear TTS audio cache"""
    tts_service = get_tts_service()
    tts_service.clear_cache()
    return {"message": "TTS cache cleared"}

